Repository mishra10008/Hactoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#39 Create 507. Perfect Number.py
  507. Perfect Number.py
Labels: hactoberfest

#33 Create The Skyline Problem
  2. Leetcode/The Skyline Problem
Labels: hactoberfest, hacktoberfest-accepted

#38 Word Search in c++
  2. Leetcode/79.word-search.cpp
Labels: hactoberfest, hacktoberfest-accepted

#36 Create Recursive Insertion Sort
  3. GeeksForGeeks/Recursive Insertion Sort
Labels: hactoberfest, hacktoberfest-accepted

#32 Median of 2 sorted arrays
  2. Leetcode/median-of-two-sorted-arrays.py
Labels: hactoberfest, hacktoberfest-accepted

#43 Create Two Sum.cpp
  2. Leetcode/Two Sum.cpp
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#42 House Robber II.cpp
  2. Leetcode/House Robber II.cpp
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#41 House Robber.cpp
  2. Leetcode/House Robber.cpp
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#40 Palindrome Partitioning II.cpp
  2. Leetcode/Palindrome Partitioning II.cpp
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#34 Added question on binary tree of finding nodes at distance k from tar…
  4. Codechef/CPP/Nodes_at_distance_k.cpp
Labels: hactoberfest, hacktoberfest-accepted

#28 Create Subtract the Product and Sum of Digits of an Integer.py
  2. Leetcode/Subtract the Product and Sum of Digits of an Integer.py
Labels: hactoberfest, hacktoberfest-accepted

#14 Without_using_semicolon.cpp
  3. GeeksForGeeks/Without_using_semicolon..cpp
Labels: hactoberfest, hacktoberfest-accepted

#15 Balanced Paranthesis
  3. GeeksForGeeks/Balanced Paranthesis.cpp
Labels: hactoberfest, hacktoberfest-accepted

#16 SNAKPROC.cpp
  1. Codeforces/Watermelon.cpp
  4. Codechef/CPP/SNAKPROC.cpp
Labels: hactoberfest, hacktoberfest-accepted

#17 Create N-Queens_Adarsh_Mohanty
  2. Leetcode/N-Queens_Adarsh_Mohanty
Labels: hactoberfest, hacktoberfest-accepted

#19 coinchange2
  2. Leetcode/coinchange2
Labels: hactoberfest, hacktoberfest-accepted

#20 Added Leap year program in Python
  5. Other/LeapYear.py
Labels: hactoberfest, hacktoberfest-accepted

#22 Remove duplicate from sorted array
  2. Leetcode/Remove_duplicate_from_sorted_array.java
Labels: hactoberfest, hacktoberfest-accepted

#24 Create main.cpp
  main.cpp
Labels: hactoberfest, hacktoberfest-accepted

#18 Create Nth_root_of_a_number.cpp
  Nth_root_of_a_number.cpp
Labels: hactoberfest, hacktoberfest-accepted

#25 Create count odd numbers in an interval range.py
  2. Leetcode/count odd numbers in an interval range.py
Labels: hactoberfest, hacktoberfest-accepted

#27 Added Combination Sum 2 Code
  2. Leetcode/Combination Sum 2
Labels: hactoberfest, hacktoberfest-accepted

#30 Create 4. Median of Two Sorted Arrays.java
  2. Leetcode/4. Median of Two Sorted Arrays.java
  2. Leetcode/Reverse Nodes in k-Groups.java
Labels: hactoberfest, hacktoberfest-accepted

#29 Added the Memoisation and tabulation approach for LIS
  2. Leetcode/Longest Increasing Subsequence(LIS).cpp
Labels: hactoberfest, hacktoberfest-accepted

#26 Create Average Salary Excluding the Minimum and Maximum Salary.py
  2. Leetcode/Average Salary Excluding the Minimum and Maximum Salary.py
Labels: hactoberfest, hacktoberfest-accepted

#46 Create Prim-Algo.cpp
  5. Other/Prim-Algo.cpp
Labels: enhancement, good first issue, hactoberfest, hacktoberfest-accepted

#45 Dijkstra_Algorithm.cpp
  5. Other/Dijkstra_Algorithm.cpp
Labels: enhancement, good first issue, hactoberfest, hacktoberfest-accepted

#44 Bellman-Ford-Algorithm.cpp
  5. Other/Bellman-Ford-Algorithm.cpp
Labels: enhancement, good first issue, hactoberfest, hacktoberfest-accepted

#47 Create Valid Anagram.cpp
  5. Other/Valid Anagram.cpp
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#49 Create Sliding Window Maximum.cpp
  5. Other/Sliding Window Maximum.cpp
Labels: hactoberfest, hacktoberfest-accepted

#48 Create Search a 2D Matrix II.cpp
  5. Other/Search a 2D Matrix II.cpp
Labels: hactoberfest, hacktoberfest-accepted

#50 Create Product of Array Except Self.cpp
  5. Other/Product of Array Except Self.cpp
Labels: good first issue, hactoberfest, hacktoberfest-accepted

#51 Create Sudoku Solver.cpp
  5. Other/Sudoku Solver.cpp
Labels: hactoberfest, hacktoberfest-accepted

#52 Create adjacency_matrix.cpp
  5. Other/adjacency_matrix.cpp
Labels: hactoberfest, hacktoberfest-accepted

#53 Create dfs.cpp
  5. Other/dfs.cpp
Labels: hactoberfest, hacktoberfest-accepted

#54 Create Merge-Two-Binary-Trees.cpp
  5. Other/Merge-Two-Binary-Trees.cpp
Labels: hactoberfest, hacktoberfest-accepted
